## server settings
server:
  address: 127.0.0.1
  forward-headers-strategy: NATIVE
  port: 8081
  servlet:
    context-path: /
  shutdown: graceful

## credentials for the domainrobot sdk    
autodns:
  context: 4
  url: https://api.autodns.com/v1

## ddauto congig
ddauto:
  zone-validation-enabled: true
  zone-log-page-enabled: false
  zone-log-file-pattern: ./ddauto-zone*

## import individual config
spring:
  config:
    import: optional:file:./ddauto.yml

## spring security
  security:
    user:
      name: dyndns
      password: test123
